apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo-service
  labels:
    app: devsecops-demo
spec:
  type: LoadBalancer
  selector:
    app: devsecops-demo
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
