name: Secure CI/CD with OIDC

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_NAME: devsecops-demo
  NODE_VERSION: '18'

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

jobs:
  security-scan:
    name: 🔒 Security Scanning
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  build-and-test:
    name: 🏗️ Build and Test
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Run linting
      run: npm run lint

  build-container:
    name: 🐳 Build Container
    runs-on: ubuntu-latest
    needs: build-and-test
    outputs:
      image-tag: ${{ steps.image-tag.outputs.tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Generate image tag
      id: image-tag
      run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
        
    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Login to ACR
      run: az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}
      
    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }} .
        docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}
        
    - name: Scan container image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}
        format: 'sarif'
        output: 'trivy-image-results.sarif'
        
    - name: Upload image scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-image-results.sarif'

  deploy-development:
    name: 🚀 Deploy to Development
    runs-on: ubuntu-latest
    needs: build-container
    if: github.ref == 'refs/heads/develop'
    environment: development
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Get AKS credentials
      run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}
          
    - name: Deploy to Development
      run: |
        sed -i 's|{{IMAGE_TAG}}|${{ needs.build-container.outputs.image-tag }}|g' k8s/deployment.yml
        sed -i 's|{{ACR_LOGIN_SERVER}}|${{ env.ACR_LOGIN_SERVER }}|g' k8s/deployment.yml
        sed -i 's|{{IMAGE_NAME}}|${{ env.IMAGE_NAME }}|g' k8s/deployment.yml
        kubectl apply -f k8s/namespace.yml
        kubectl apply -f k8s/ -n development

  deploy-production:
    name: 🌟 Deploy to Production
    runs-on: ubuntu-latest
    needs: build-container
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Get AKS credentials
      run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}
          
    - name: Deploy to Production
      run: |
        sed -i 's|{{IMAGE_TAG}}|${{ needs.build-container.outputs.image-tag }}|g' k8s/deployment.yml
        sed -i 's|{{ACR_LOGIN_SERVER}}|${{ env.ACR_LOGIN_SERVER }}|g' k8s/deployment.yml
        sed -i 's|{{IMAGE_NAME}}|${{ env.IMAGE_NAME }}|g' k8s/deployment.yml
        kubectl apply -f k8s/namespace.yml
        kubectl apply -f k8s/ -n production
